### ISSUE TITLE
Progress of resource registration not listed in workflows

### ISSUE THREAD

**Issue by KostasPatroumpas** [SLIPO-EU/workbench#13]
Once registration of a resource is created and successfully submitted to the scheduler, the corresponding transformation task is not listed in the workflows. It is only visible at the bottom of the Dashboard, and when the user clicks on its title, an error occurs.

The issue is that there seems to be no information about the progress of this task (running, stopped, failed...). Only once the registration process terminates successfully, this resource appears in the list of available resources. What happens if registration fails and how the user is notified?

**Comment by jkouvar** [comment]
Closed in c8eda3b.
